databases:
  - name: my_appdb
    plan: free
    databaseName: grnlite_postgresql
    user: my_app

# Exported from Render on 2024-12-09T19:25:51Z
services:
- type: web
  name: GRNLITE
  runtime: python
  repo: https://github.com/JSander72/GRNLITE
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: my_appdb
      property: connectionString
  - key: DEBUG
    value: "False"
  - key: DJANGO_ALLOWED_HOSTS
    value: "grnlite.onrender.com,127.0.0.1,localhost"
  - key: USER
    sync: false
  - key: PORT
    sync: false
  - key: PASSWORD
    sync: false
  - key: NAME
    sync: false
  - key: HOST
    sync: false
  - key: ENGINE
    sync: false
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    sync: false
  - key: JWT_REFRESH_SECRET
    sync: false
  - key: DJANGO_SECRET_KEY
    sync: false
  region: ohio
  buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && npm install
  startCommand: gunicorn grnlite.wsgi:application --bind 0.0.0.0:$PORT

- type: web
  name: GRNLITE-KeepAlive
  runtime: node
  repo: https://github.com/JSander72/GRNLITE
  plan: free
  envVars:
  - key: NODE_ENV
    value: production
  - key: RENDER_EXTERNAL_URL
    value: https://grnlite.onrender.com
  - key: APP_URL
    value: https://grnlite.onrender.com
  - key: HEALTH_ENDPOINT
    value: /
  region: ohio
  buildCommand: npm install
  startCommand: node standalone-keepalive.js
version: "1"



