# Generated by Django 5.1.4 on 2025-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Feedback category name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the category", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this category active and selectable?",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manuscript",
            name="feedback_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selected feedback questions for this manuscript",
                related_name="manuscripts",
                to="my_app.feedbackquestion",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="feedback_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selected feedback categories for this manuscript",
                related_name="manuscripts",
                to="my_app.feedbackcategory",
            ),
        ),
    ]
