# Generated by Django 5.1.4 on 2025-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="manuscripts/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="cover_art",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/cover_art/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="file_path",
            field=models.FileField(upload_to="uploads/manuscript/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="nda_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/nda/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="plot_summary",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
