# Generated by Django 5.1.4 on 2025-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(default="default_user_type", max_length=50),
        ),
    ]
