# Generated by Django 5.1.4 on 2025-01-19 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_usertoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertoken",
            old_name="refresh_token",
            new_name="token",
        ),
        migrations.AddField(
            model_name="usertoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
