# Generated by Django 5.1.4 on 2025-01-14 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_alter_profile_user_alter_profile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
    ]
