# Generated by Django 5.1.4 on 2025-01-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0003_remove_profile_bio_remove_profile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("reader", "Reader"), ("author", "Author")],
                default="reader",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.customuser"
            ),
        ),
    ]
