# Generated by Django 5.1.4 on 2025-01-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0003_rename_refresh_token_usertoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(default="regular", max_length=50),
        ),
    ]
