# Generated by Django 5.1.4 on 2025-01-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0003_remove_profile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("reader", "Reader"), ("admin", "Admin")],
                default="reader",
                max_length=50,
            ),
        ),
    ]
