# Generated by Django 5.1.4 on 2025-02-13 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0003_alter_profile_created_at_alter_profile_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
