# Generated by Django 5.1.4 on 2025-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0004_alter_profile_role_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="genre",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
    ]
