# Generated by Django 5.1.4 on 2025-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0004_alter_profile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="cover",
            field=models.ImageField(upload_to="manuscripts/covers/"),
        ),
    ]
