# Generated by Django 5.1.4 on 2025-01-16 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("my_app", "0004_remove_profile_role_profile_user_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="customuser",
        #     name="genres",
        # ),
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("beta_reader", "Beta Reader"),
                    ("editor", "Editor"),
                ],
                default="author",
                help_text="Role of the user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="betareader",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                help_text="Genres the beta reader is interested in",
                related_name="beta_readers",
                to="my_app.genre",
            ),
        ),
        migrations.AlterField(
            model_name="betareader",
            name="user",
            field=models.OneToOneField(
                help_text="The user who is a beta reader",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beta_reader_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="cover_art",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/cover_art/% Y/% m/% d/"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="file_path",
            field=models.FileField(upload_to="uploads/manuscript/% Y/% m/% d/"),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="nda_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/nda/% Y/% m/% d/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="User who owns the profile",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CustomUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customuser",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manuscript_keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.keyword"
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.manuscript",
                    ),
                ),
            ],
            options={
                "db_table": "my_app_manuscript_keywords",
            },
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords associated with the manuscript",
                related_name="manuscripts",
                through="my_app.Manuscript_keywords",
                to="my_app.keyword",
            ),
        ),
    ]
