# Generated by Django 5.1.4 on 2025-01-16 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "my_app",
            "0005_remove_customuser_genres_remove_notification_is_read_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="genres",
        ),
    ]
