# Generated by Django 5.1.4 on 2025-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscripts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manuscript",
        ),
    ]
