name: Django CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]
    env:
      DJANGO_SETTINGS_MODULE: grnlite.settings

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests with Coverage
        run: |
          pytest --cov=.
      - name: Lint Code
        run: |
          flake8 .
      - name: Build for Production
        run: |
          python manage.py collectstatic --noinput
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying to Render..."
          curl "$deploy_url"