name: Django CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]
    env:
      DJANGO_SETTINGS_MODULE: grnlite.settings

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Dependencies, Run Tests, and Lint
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest pytest-cov
          pytest --cov=. -q
          flake8 .
      
      - name: Build for Production
        run: |
          python manage.py collectstatic --noinput
          - name: Upload logs as artifacts
          uses: actions/upload-artifact@v3
          with:
            name: logs
            path: <path/to/your/logs>
      
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying to Render..."
          curl "$deploy_url"
